// Code generated by mockery v1.0.0
package mocks

import collections "github.com/crowleyfelix/star-wars-api/api/database/mongodb/collections"
import mock "github.com/stretchr/testify/mock"
import models "github.com/crowleyfelix/star-wars-api/api/database/mongodb/models"

// Planets is an autogenerated mock type for the Planets type
type Planets struct {
	mock.Mock
}

// Delete provides a mock function with given fields: _a0
func (_m *Planets) Delete(_a0 int) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: _a0, _a1
func (_m *Planets) Find(_a0 *collections.PlanetSearchQuery, _a1 *collections.Pagination) (*models.PlanetPage, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *models.PlanetPage
	if rf, ok := ret.Get(0).(func(*collections.PlanetSearchQuery, *collections.Pagination) *models.PlanetPage); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PlanetPage)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*collections.PlanetSearchQuery, *collections.Pagination) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: _a0
func (_m *Planets) FindByID(_a0 int) (*models.Planet, error) {
	ret := _m.Called(_a0)

	var r0 *models.Planet
	if rf, ok := ret.Get(0).(func(int) *models.Planet); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Planet)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: _a0
func (_m *Planets) Insert(_a0 *models.Planet) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Planet) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: _a0
func (_m *Planets) Update(_a0 *models.Planet) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Planet) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
