version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-api
    env_file:
      - .env.example
    ports:
      - "8888:8888"
  mongo:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-mongo
    ports:
      - 27017:27017
      - 28017:28017      