// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/crowleyfelix/star-wars-api/api/models"
import services "github.com/crowleyfelix/star-wars-api/api/services"

// Planet is an autogenerated mock type for the Planet type
type Planet struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *Planet) Create(_a0 *models.Planet) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Planet) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: _a0
func (_m *Planet) Get(_a0 int) (*models.Planet, error) {
	ret := _m.Called(_a0)

	var r0 *models.Planet
	if rf, ok := ret.Get(0).(func(int) *models.Planet); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Planet)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Remove provides a mock function with given fields: _a0
func (_m *Planet) Remove(_a0 int) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Search provides a mock function with given fields: _a0, _a1
func (_m *Planet) Search(_a0 *services.PlanetSearchParams, _a1 *services.Pagination) (*models.PlanetPage, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *models.PlanetPage
	if rf, ok := ret.Get(0).(func(*services.PlanetSearchParams, *services.Pagination) *models.PlanetPage); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PlanetPage)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*services.PlanetSearchParams, *services.Pagination) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
