// Code generated by mockery v1.0.0
package mocks

import mgo "gopkg.in/mgo.v2"
import mock "github.com/stretchr/testify/mock"

// SessionPool is an autogenerated mock type for the SessionPool type
type SessionPool struct {
	mock.Mock
}

// Release provides a mock function with given fields: _a0
func (_m *SessionPool) Release(_a0 *mgo.Session) {
	_m.Called(_a0)
}

// Session provides a mock function with given fields:
func (_m *SessionPool) Session() (*mgo.Session, error) {
	ret := _m.Called()

	var r0 *mgo.Session
	if rf, ok := ret.Get(0).(func() *mgo.Session); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mgo.Session)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
