# Build
FROM golang:latest as builder 

ENV GOPATH "/"
ENV APP_PATH "/src/github.com/crowleyfelix/star-wars-api/server"

ADD ./server $APP_PATH
WORKDIR $APP_PATH
RUN go get -d
RUN CGO_ENABLED=0 GOOS=linux go build -o /server ./main.go

# Serve
FROM scratch

WORKDIR /root/
COPY --from=builder /server /root
COPY --from=builder /etc/ssl /etc/ssl
ENV PATH "$PATH:/root"

CMD [ "./server" ]