// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import swapi "github.com/crowleyfelix/star-wars-api/src/clients/swapi"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// PlanetFilms provides a mock function with given fields: name
func (_m *Client) PlanetFilms(name string) ([]swapi.Film, error) {
	ret := _m.Called(name)

	var r0 []swapi.Film
	if rf, ok := ret.Get(0).(func(string) []swapi.Film); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]swapi.Film)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
