// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

// Delete provides a mock function with given fields:
func (_m *Controller) Delete() {
	_m.Called()
}

// Get provides a mock function with given fields:
func (_m *Controller) Get() {
	_m.Called()
}

// Post provides a mock function with given fields:
func (_m *Controller) Post() {
	_m.Called()
}

// Put provides a mock function with given fields:
func (_m *Controller) Put() {
	_m.Called()
}
